accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views


app_name = "accounts"

urlpatterns = [
    path("signup/", views.UserCreateView.as_view(), name="signup"),
    path("login/", LoginView.as_view(template_name="accounts/login.html", next_page="projects:project_list"), name="login"),
    path("logout/", LogoutView.as_view(next_page="accounts:login"), name="logout"),
    path("profile/", views.UserUpdateView.as_view(), name="profile"),
]

devtasker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('tasks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from . import views


app_name = "tasks"

urlpatterns = [
    path("tasks/<int:pk>/", views.TaskDetailView.as_view(), name="task_detail"),
    path("projects/<int:project_id>/tasks/create/", views.TaskCreateView.as_view(), name="task_create"),
    path("tasks/<int:pk>/edit/", views.TaskUpdateView.as_view(), name="task_edit"),
    path("tasks/<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    bio = models.TextField(blank=True)
    job_title = models.CharField(max_length=150, blank=True)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import CustomUserCreationForm
from .models import User


class UserCreateView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("accounts:login")

    def form_valid(self, form):
        messages.success(self.request, "Your account has been created. You can now log in.")
        return super().form_valid(form)
    
class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["first_name", "last_name", "bio", "job_title", "avatar"]
    template_name ="accounts/profile.html"
    success_url = reverse_lazy("accounts:profile")
    
    def get_object(self):
        return self.request.user

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Log In</button>
    </form>
    <a href="{% url 'accounts:signup' %}">Don't have an account? Sign up</a>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block title %}{{ user.first_name }} {{ user.last_name }}{% endblock %}

{% block content %}
    <h2>My Profile</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save</button>
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
    <a href="{% url 'accounts:login' %}">Already have an account? Log in</a>
{% endblock %}