accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views


app_name = "accounts"

urlpatterns = [
    path("signup/", views.UserCreateView.as_view(), name="signup"),
    path("login/", LoginView.as_view(template_name="accounts/login.html", next_page="projects:project_list"), name="login"),
    path("logout/", LogoutView.as_view(next_page="accounts:login"), name="logout"),
    path("profile/", views.UserUpdateView.as_view(), name="profile"),
]

devtasker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('tasks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from . import views


app_name = "tasks"

urlpatterns = [
    path("tasks/<int:pk>/", views.TaskDetailView.as_view(), name="task_detail"),
    path("projects/<int:project_id>/tasks/create/", views.TaskCreateView.as_view(), name="task_create"),
    path("tasks/<int:pk>/edit/", views.TaskUpdateView.as_view(), name="task_edit"),
    path("tasks/<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"),
]

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}DevTasker{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">DevTasker</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'projects:project_list' %}">Projects</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              {% if user.is_authenticated %}
                  <a href="{% url 'accounts:profile' %}" class="me-2 text-decoration-none">
                    <img src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}"
                    class="rounded-circle" 
                    alt="Profile"
                    style="width: 40px; height: 40px; object-fit: cover;">
                  </a>
                  <form action="{% url 'accounts:logout' %}" method="post" class="d-inline">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-outline-light btn-sm">Logout</button>
                  </form> 
              {% else %}
                  <a class="btn btn-outline-light btn-sm" href="{% url 'accounts:login' %}">Log In</a> 
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</body>
</html>